//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsTestAPI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instance
    {
        public Instance()
        {
            this.UserAnswers = new HashSet<UserAnswer>();
        }
    
        public int Id { get; set; }
        public int CreatorID { get; set; }
        public int CandidateID { get; set; }
        public bool IsFinished { get; set; }
        public bool IsScored { get; set; }
        public Nullable<int> Score { get; set; }
        public int TestID { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string GuidUrl { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<UserAnswer> UserAnswers { get; set; }
    }
}
