//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsTestAPI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestsInTechnology
    {
        public int Id { get; set; }
        public int TestID { get; set; }
        public int TechnologyID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Technology Technology { get; set; }
        public virtual Test Test { get; set; }
    }
}
