//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsTestAPI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Instances = new HashSet<Instance>();
            this.Instances1 = new HashSet<Instance>();
            this.Tests = new HashSet<Test>();
            this.Candidates = new HashSet<Candidate>();
            this.CandidatesInLanguages = new HashSet<CandidatesInLanguage>();
            this.CandidatesInTechnologies = new HashSet<CandidatesInTechnology>();
            this.Specialists = new HashSet<Specialist>();
            this.SpecialistsInTechnologies = new HashSet<SpecialistsInTechnology>();
            this.UsersInRoles = new HashSet<UsersInRole>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Instance> Instances { get; set; }
        public virtual ICollection<Instance> Instances1 { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
        public virtual ICollection<Candidate> Candidates { get; set; }
        public virtual ICollection<CandidatesInLanguage> CandidatesInLanguages { get; set; }
        public virtual ICollection<CandidatesInTechnology> CandidatesInTechnologies { get; set; }
        public virtual ICollection<Specialist> Specialists { get; set; }
        public virtual ICollection<SpecialistsInTechnology> SpecialistsInTechnologies { get; set; }
        public virtual ICollection<UsersInRole> UsersInRoles { get; set; }
    }
}
