//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsTestAPI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswer
    {
        public int Id { get; set; }
        public int QuestionID { get; set; }
        public int InstanceID { get; set; }
        public string Choices { get; set; }
        public string OpenQuestionAnswer { get; set; }
        public int Points { get; set; }
        public bool IsScored { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Instance Instance { get; set; }
        public virtual Question Question { get; set; }
    }
}
